### ISSUE TITLE
[Enhancement] Move the curve graph below the stats

### ISSUE THREAD

**Issue by milroneth** [NGnius/Fantastic#1]
I believe the current layout "just happened" by adding Current fan speed and Current temperature display later on during development.

I'd love to see the graph with its interpolation toggle be moved to the bottom, after the status lines, so that they remain static when Fantastic itself is toggled. I'm using them much more when deciding to enable of disable the plugin, than I do to change the curve—which honestly, I don't do at all, I set up the curve I wanted once, adjusted it a bit later and now that I'm happy with it it's just sitting there undisturbed.

Currently having to scroll up and down constantly feels like a chore...

**Comment by NGnius** [comment]
Done in v0.3.0. Since I had to rewrite the UI anyway, it was pretty easy to re-organize the order of it.
