### ISSUE TITLE
Fantastic no longer working on latest Decky Loader (2.4.5)

### ISSUE THREAD

**Issue by v-flashpoint** [NGnius/Fantastic#10]
Hi all,

I updated my Decky Loader last night to version 2.4.5, and ever since then the Fantastic plugin hasn't been able to control my fans. Instead I've been back to the standard (and mostly useless) Steam version that spins up crazily every few seconds.

I'm using v0.3.4 of Fantastic, and have tried reinstalling the plugin, restarting the Steam Deck, rolling back to an earlier version of the plugin, but nothing's worked. 

Not sure if I've just ended up updating a bit too much, as I noticed my Decky Loader was set to update on the prerelease branch rather than stable, but I wanted to let you guys know in the hope it's not just me!

I've attached a screenshot to show the issue.

![steamuserimages-a akamaihd](https://user-images.githubusercontent.com/99752646/203944646-59a4bcf8-0950-4776-89bb-eb5b9dde2348.jpg)

**Comment by NGnius** [comment]
What version of SteamOS are you using?

**Comment by v-flashpoint** [comment]
3.3.2 (20221005.1)

**Comment by NGnius** [comment]
Looks like the method that I was using to disable the system's built-in fan control was removed. I'll see if I can fix that soon-ish.

For now, it should work fine if you manually disable the updated fan control (in Settings > System)
