### ISSUE TITLE
Impossible to compile - nRPC 0.10.0 not published

### ISSUE THREAD

**Issue by Kiblyn11** [NGnius/Fantastic#16]
It is not possible to compile ourselves Fantastic because of missing dependency nRPC 0.10.0 (from usdpl).
Latest nRPC version on your repo is 0.8.0

**Comment by NGnius** [comment]
Works on my machine /j

nRPC v0.10 isn't stable yet, same with Fantastic v.0.5.0, so I'm not too surprised that I broke something. I'll push the latest nRPC code once I've got access to my dev PC again (Tuesday probably).

**Comment by Kiblyn11** [comment]
Sorry, my bad.

I assumed master was the decky version.
Switching to decky branch it's better, though I had to use the build-docker script.
Regular script throw errors `can't find crate for `core``.
