### ISSUE TITLE
Cpu is running at 100 percent when i install fantastic 3.0. 2.0 does not have this issue

### ISSUE THREAD

**Issue by donannis** [NGnius/Fantastic#3]
Tested by removing fantastic 3.0  the cpu went back to normal.  reinstalled 3.0 fantastic adn cpu went back to 100 percent usage. multiple times. Defaulted to 2.0 to save cpu being on full blast.

**Comment by NGnius** [comment]
Oh yeah, I see where it is. Making a new release now
