### ISSUE TITLE
Version 0.3.x Not in Plugin store

### ISSUE THREAD

**Issue by cimba007** [NGnius/Fantastic#5]
See Titel. Is there any chance to get them in the store?

**Comment by NGnius** [comment]
I submitted the request basically as soon as I released v0.3.0, this is the Decky team's problem right now https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/19

As far as I heard, the Decky devs want to setup their system to automatically build everything to do with the plugin, so for Fantastic that requires them to support my setup and then I have to write a build script (adding 2 Rust toolchains). It seems like a lot of extra work for them and me, but I'll probably go ahead with it once they've done their part. I'm not happy about them adding arbitrary requirements to get onto their "open" store, but I don't want to get involved in their internal politics.

**Comment by NGnius** [comment]
There is now a version on the store, thanks to Train, so I'm closing this
